'use client';

import { useState, useEffect } from "react";

const EXAM_INFO = {
  lezen: { name: "Lezen", icon: "📖", duration: "65 min", format: "電腦作答，閱讀文章回答選擇題", tip: "會出現廣告、信件、通知、說明書等日常文本" },
  luisteren: { name: "Luisteren", icon: "🎧", duration: "45 min", format: "電腦作答，聽對話/廣播回答選擇題，每段聽 1-2 次", tip: "注意聽數字、時間、地點等關鍵資訊" },
  schrijven: { name: "Schrijven", icon: "✏️", duration: "40 min", format: "紙筆作答，4 題寫作（短信、填表、回覆邀請等）", tip: "重點是傳達訊息，文法不完美沒關係" },
  spreken: { name: "Spreken", icon: "🎙️", duration: "35 min", format: "對電腦錄音，看影片/圖片回答問題（2025年起無選擇題，全部口說）", tip: "短句清楚比長句含糊好，被理解最重要" },
  knm: { name: "KNM", icon: "🏛️", duration: "45 min", format: "40 題選擇題，涵蓋荷蘭社會、政治、醫療、教育、住房", tip: "2025年7月改版，注意用新版教材" },
};

const COURSE_DATA = {
  1:{theme:"Bij de huisarts",themeZh:"看醫生",vocab:[{nl:"de huisarts",zh:"家庭醫生",example:"Ik ga naar de huisarts."},{nl:"een afspraak maken",zh:"預約",example:"Ik wil een afspraak maken."},{nl:"pijn",zh:"痛",example:"Ik heb pijn in mijn buik."},{nl:"het recept",zh:"處方",example:"De dokter geeft me een recept."},{nl:"koorts",zh:"發燒",example:"Ik heb koorts sinds gisteren."}],dialogue:{context:"你打電話給診所預約看醫生",lines:[{speaker:"Receptionist",text:"Huisartsenpraktijk, goedemorgen. Waarmee kan ik u helpen?"},{speaker:"Jij",text:"Goedemorgen, ik wil graag een afspraak maken."},{speaker:"Receptionist",text:"Wat zijn uw klachten?"},{speaker:"Jij",text:"Ik heb pijn in mijn keel en ik heb koorts."},{speaker:"Receptionist",text:"Kunt u morgenochtend om tien uur komen?"},{speaker:"Jij",text:"Ja, dat kan. Dank u wel."}]},exercise:{instruction:"把以下句子翻譯成荷蘭文：",questions:[{zh:"我想預約看醫生。",answer:"Ik wil een afspraak maken bij de huisarts."},{zh:"我肚子痛。",answer:"Ik heb pijn in mijn buik."},{zh:"醫生給我一張處方。",answer:"De dokter geeft me een recept."}]},speaking:"錄音唸三遍：「Ik heb pijn in mijn keel en ik heb koorts.」\n\n發音重點：'pijn' 唸 /pɛin/（像「派恩」），'koorts' 的 oo 是長音。",listening:"YouTube 搜尋「bij de huisarts Nederlands A2」看一段 2 分鐘影片，回來告訴我病人有什麼症狀。",goldenSentence:"Ik wil graag een afspraak maken bij de huisarts.",goldenSentenceZh:"我想在家庭醫生那裡預約。",examFocus:"spreken"},
  2:{theme:"In de supermarkt",themeZh:"在超市",vocab:[{nl:"de aanbieding",zh:"特價",example:"Deze kaas is in de aanbieding."},{nl:"de kassa",zh:"收銀台",example:"Er is een lange rij bij de kassa."},{nl:"het bonnetje",zh:"收據",example:"Wilt u het bonnetje?"},{nl:"een tasje",zh:"袋子",example:"Mag ik een tasje, alstublieft?"},{nl:"pinnen",zh:"刷卡付款",example:"Kan ik hier pinnen?"}],dialogue:{context:"你在 Albert Heijn 結帳",lines:[{speaker:"Kassier",text:"Goedemiddag! Heeft u een bonuskaart?"},{speaker:"Jij",text:"Ja, hier alstublieft."},{speaker:"Kassier",text:"Dat wordt twaalf euro vijftig."},{speaker:"Jij",text:"Kan ik pinnen?"},{speaker:"Kassier",text:"Ja, natuurlijk. Wilt u het bonnetje?"},{speaker:"Jij",text:"Nee, dank u. Fijne dag!"}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"這個起司在特價。",answer:"Deze kaas is in de aanbieding."},{zh:"我可以刷卡嗎？",answer:"Kan ik pinnen?"},{zh:"我不需要收據。",answer:"Ik hoef het bonnetje niet."}]},speaking:"錄音唸三遍：「Dat wordt twaalf euro vijftig.」\n\n發音重點：'twaalf' 的 tw 連讀，'vijftig' 的 ij 唸 /ɛi/。",listening:"YouTube 搜尋「in de supermarkt Nederlands」看影片，回來說那個人買了什麼。",goldenSentence:"Kan ik hier pinnen?",goldenSentenceZh:"我可以在這裡刷卡嗎？",examFocus:"luisteren"},
  3:{theme:"Op het gemeentehuis",themeZh:"在市政廳",vocab:[{nl:"het gemeentehuis",zh:"市政廳",example:"Ik moet naar het gemeentehuis."},{nl:"een paspoort",zh:"護照",example:"Ik wil een nieuw paspoort aanvragen."},{nl:"de inschrijving",zh:"登記",example:"Ik kom voor mijn inschrijving."},{nl:"het formulier",zh:"表格",example:"U moet dit formulier invullen."},{nl:"het huurcontract",zh:"租約",example:"Heeft u uw huurcontract meegenomen?"}],dialogue:{context:"你去市政廳辦理地址登記",lines:[{speaker:"Medewerker",text:"Goedemorgen, heeft u een afspraak?"},{speaker:"Jij",text:"Ja, ik heb een afspraak om elf uur. Ik kom voor mijn inschrijving."},{speaker:"Medewerker",text:"Heeft u uw paspoort en huurcontract meegenomen?"},{speaker:"Jij",text:"Ja, hier zijn ze."},{speaker:"Medewerker",text:"Goed. Wilt u dit formulier invullen, alstublieft?"},{speaker:"Jij",text:"Ja, natuurlijk."}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"我需要去市政廳。",answer:"Ik moet naar het gemeentehuis."},{zh:"我想申請新護照。",answer:"Ik wil een nieuw paspoort aanvragen."},{zh:"請填寫這張表格。",answer:"Wilt u dit formulier invullen, alstublieft?"}]},speaking:"錄音唸三遍：「Ik kom voor mijn inschrijving.」\n\n發音重點：'inschrijving' 的 sch 是喉音 /sx/，多練這個音。",listening:"YouTube 搜尋「gemeentehuis Nederlands」看影片，回來說那個人去辦什麼事。",goldenSentence:"Ik kom voor mijn inschrijving.",goldenSentenceZh:"我是來辦登記的。",examFocus:"schrijven"},
  4:{theme:"Met de trein reizen",themeZh:"搭火車",vocab:[{nl:"het perron",zh:"月台",example:"De trein vertrekt van perron drie."},{nl:"de vertraging",zh:"誤點",example:"Er is een vertraging van tien minuten."},{nl:"enkele reis",zh:"單程",example:"Een enkele reis naar Amsterdam, alstublieft."},{nl:"overstappen",zh:"轉車",example:"U moet overstappen in Almere."},{nl:"de OV-chipkaart",zh:"交通卡",example:"Vergeet niet in te checken met uw OV-chipkaart."}],dialogue:{context:"你在 Lelystad Centrum 車站要去 Amsterdam",lines:[{speaker:"Jij",text:"Een enkele reis naar Amsterdam Centraal, alstublieft."},{speaker:"Loket",text:"Dat is negen euro tachtig. Heeft u een OV-chipkaart?"},{speaker:"Jij",text:"Ja. Van welk perron vertrekt de trein?"},{speaker:"Loket",text:"Perron twee. U moet overstappen in Almere."},{speaker:"Jij",text:"Hoe laat vertrekt de volgende trein?"},{speaker:"Loket",text:"Over vijf minuten."}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"火車誤點十分鐘。",answer:"De trein heeft een vertraging van tien minuten."},{zh:"一張到阿姆斯特丹的單程票。",answer:"Een enkele reis naar Amsterdam, alstublieft."},{zh:"你要在 Almere 轉車。",answer:"U moet overstappen in Almere."}]},speaking:"錄音唸三遍：「Een enkele reis naar Amsterdam Centraal, alstublieft.」\n\n發音重點：'enkele' 重音第一音節，'alstublieft' 略為 /alstybli:ft/。",listening:"YouTube 搜尋「trein reizen Nederland」看影片，回來說那個人要去哪、要不要轉車。",goldenSentence:"Een enkele reis naar Amsterdam Centraal, alstublieft.",goldenSentenceZh:"請給我一張到阿姆斯特丹中央車站的單程票。",examFocus:"lezen"},
  5:{theme:"De buren",themeZh:"鄰居",vocab:[{nl:"de buren",zh:"鄰居",example:"Mijn buren zijn heel aardig."},{nl:"kennismaken",zh:"認識",example:"Ik wil graag kennismaken."},{nl:"verhuizen",zh:"搬家",example:"Ik ben net verhuisd naar deze straat."},{nl:"uitnodigen",zh:"邀請",example:"Ik wil je uitnodigen voor koffie."},{nl:"het geluid",zh:"噪音",example:"Er is veel geluid 's avonds."}],dialogue:{context:"你剛搬家，去跟隔壁鄰居打招呼",lines:[{speaker:"Jij",text:"Hallo, ik ben je nieuwe buurman. Ik ben net verhuisd."},{speaker:"Buurvrouw",text:"Oh, welkom! Ik ben Maria. Leuk om kennis te maken."},{speaker:"Jij",text:"Insgelijks! Ik woon hier met mijn vrouw."},{speaker:"Buurvrouw",text:"Wat leuk. Als je iets nodig hebt, klop gerust aan."},{speaker:"Jij",text:"Dank je wel! Misschien kunnen we een keer koffie drinken?"},{speaker:"Buurvrouw",text:"Ja, heel graag! Zaterdag?"}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"我剛搬到這條街。",answer:"Ik ben net verhuisd naar deze straat."},{zh:"很高興認識你。",answer:"Leuk om kennis te maken."},{zh:"如果你需要什麼，儘管來敲門。",answer:"Als je iets nodig hebt, klop gerust aan."}]},speaking:"錄音唸三遍：「Leuk om kennis te maken!」\n\n發音重點：'kennis' 重音第一音節，'leuk' 的 eu 唸 /ø:/。",listening:"YouTube 搜尋「kennismaken met buren Nederlands」看影片，回來說他們聊了什麼。",goldenSentence:"Leuk om kennis te maken!",goldenSentenceZh:"很高興認識你！",examFocus:"spreken"},
  6:{theme:"Weekherhaling 1",themeZh:"第一週複習",vocab:[{nl:"herhalen",zh:"複習",example:"Laten we de woorden herhalen."},{nl:"onthouden",zh:"記住",example:"Ik kan dit woord niet onthouden."},{nl:"oefenen",zh:"練習",example:"Je moet elke dag oefenen."},{nl:"begrijpen",zh:"理解",example:"Begrijp je deze zin?"},{nl:"de fout",zh:"錯誤",example:"Ik heb een fout gemaakt."}],dialogue:{context:"綜合複習 Day 1-5",lines:[{speaker:"Vriend",text:"Hoe gaat het? Heb je al een huisarts gevonden?"},{speaker:"Jij",text:"Ja, ik heb gisteren een afspraak gemaakt."},{speaker:"Vriend",text:"En je inschrijving bij het gemeentehuis?"},{speaker:"Jij",text:"Dat heb ik vorige week gedaan."},{speaker:"Vriend",text:"Heb je al kennisgemaakt met je buren?"},{speaker:"Jij",text:"Ja, ze zijn heel aardig."}]},exercise:{instruction:"Week 1 綜合測驗：",questions:[{zh:"我昨天去看了醫生。",answer:"Ik ben gisteren naar de huisarts gegaan."},{zh:"一張到 Utrecht 的單程票。",answer:"Een enkele reis naar Utrecht, alstublieft."},{zh:"你有帶護照嗎？",answer:"Heeft u uw paspoort meegenomen?"}]},speaking:"Spreken 模擬：用荷蘭文自我介紹 30 秒（名字、住哪、工作）。錄音。",listening:"回顧 Week 1，挑最弱的情境再看一次相關影片。",goldenSentence:"Ik oefen elke dag een beetje Nederlands.",goldenSentenceZh:"我每天練一點荷蘭文。",examFocus:"spreken"},
  7:{theme:"In het restaurant",themeZh:"在餐廳",vocab:[{nl:"de menukaart",zh:"菜單",example:"Mag ik de menukaart, alstublieft?"},{nl:"bestellen",zh:"點餐",example:"Ik wil graag bestellen."},{nl:"de rekening",zh:"帳單",example:"Mag ik de rekening, alstublieft?"},{nl:"het hoofdgerecht",zh:"主菜",example:"Als hoofdgerecht wil ik de vis."},{nl:"de fooi",zh:"小費",example:"In Nederland is de fooi niet verplicht."}],dialogue:{context:"你和朋友在餐廳吃飯",lines:[{speaker:"Ober",text:"Goedenavond. Heeft u gereserveerd?"},{speaker:"Jij",text:"Ja, op naam van Chen, voor twee personen."},{speaker:"Ober",text:"Wilt u iets drinken?"},{speaker:"Jij",text:"Twee koffie, alstublieft."},{speaker:"Ober",text:"En wat wilt u eten?"},{speaker:"Jij",text:"Ik wil graag de stamppot als hoofdgerecht."}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"請給我菜單。",answer:"Mag ik de menukaart, alstublieft?"},{zh:"我想點餐。",answer:"Ik wil graag bestellen."},{zh:"可以給我帳單嗎？",answer:"Mag ik de rekening, alstublieft?"}]},speaking:"Spreken 模擬：想像一張餐廳圖片，用 3-4 句描述圖中的人在做什麼。錄音 30 秒。",listening:"YouTube 搜尋「in het restaurant Nederlands A2」看影片，記下他們點了什麼。",goldenSentence:"Ik wil graag de stamppot als hoofdgerecht.",goldenSentenceZh:"我主菜想點 stamppot。",examFocus:"spreken"},
  8:{theme:"Een huis zoeken",themeZh:"找房子",vocab:[{nl:"huren",zh:"租",example:"Ik wil een appartement huren."},{nl:"de huur",zh:"房租",example:"De huur is achthonderd euro per maand."},{nl:"de slaapkamer",zh:"臥室",example:"Het huis heeft twee slaapkamers."},{nl:"de tuin",zh:"花園",example:"Er is een kleine tuin."},{nl:"de makelaar",zh:"房仲",example:"De makelaar laat het huis zien."}],dialogue:{context:"你打電話問一間出租的公寓",lines:[{speaker:"Makelaar",text:"Goedemiddag, met Van der Berg Makelaardij."},{speaker:"Jij",text:"Goedemiddag, ik bel over het appartement op de Marktstraat."},{speaker:"Makelaar",text:"Ja, dat is nog beschikbaar. Het heeft twee slaapkamers."},{speaker:"Jij",text:"Wat is de huur per maand?"},{speaker:"Makelaar",text:"Negenhonderd euro, inclusief servicekosten."},{speaker:"Jij",text:"Kan ik een bezichtiging plannen?"}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"我想租一間公寓。",answer:"Ik wil een appartement huren."},{zh:"房租每月多少錢？",answer:"Wat is de huur per maand?"},{zh:"房子有兩間臥室。",answer:"Het huis heeft twee slaapkamers."}]},speaking:"錄音唸三遍：「Ik bel over het appartement op de Marktstraat.」",listening:"YouTube 搜尋「huis zoeken Nederland」看影片，記下房子的大小和價格。",goldenSentence:"Wat is de huur per maand?",goldenSentenceZh:"每月房租多少？",examFocus:"lezen"},
  9:{theme:"Op de bank",themeZh:"在銀行",vocab:[{nl:"de bankrekening",zh:"銀行帳戶",example:"Ik wil een rekening openen."},{nl:"overmaken",zh:"轉帳",example:"Ik wil geld overmaken."},{nl:"de pinpas",zh:"金融卡",example:"Mijn pinpas werkt niet."},{nl:"opnemen",zh:"提款",example:"Ik wil honderd euro opnemen."},{nl:"het saldo",zh:"餘額",example:"Wat is mijn saldo?"}],dialogue:{context:"你去銀行開戶",lines:[{speaker:"Medewerker",text:"Goedemorgen, waarmee kan ik u helpen?"},{speaker:"Jij",text:"Ik wil graag een bankrekening openen."},{speaker:"Medewerker",text:"Heeft u een BSN-nummer en een identiteitsbewijs?"},{speaker:"Jij",text:"Ja, hier is mijn paspoort."},{speaker:"Medewerker",text:"U ontvangt uw pinpas binnen vijf werkdagen."},{speaker:"Jij",text:"Dank u wel. Kan ik ook internetbankieren aanvragen?"}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"我想開一個銀行帳戶。",answer:"Ik wil graag een bankrekening openen."},{zh:"我的金融卡不能用。",answer:"Mijn pinpas werkt niet."},{zh:"我要轉帳。",answer:"Ik wil geld overmaken."}]},speaking:"錄音唸三遍：「Ik wil graag een bankrekening openen.」",listening:"YouTube 搜尋「bank Nederlands A2」看影片。",goldenSentence:"Ik wil graag een bankrekening openen.",goldenSentenceZh:"我想開一個銀行帳戶。",examFocus:"schrijven"},
  10:{theme:"Telefoneren",themeZh:"打電話",vocab:[{nl:"opbellen",zh:"打電話",example:"Ik ga de school opbellen."},{nl:"een boodschap achterlaten",zh:"留言",example:"Kan ik een boodschap achterlaten?"},{nl:"terugbellen",zh:"回電",example:"Kunt u mij terugbellen?"},{nl:"in gesprek",zh:"通話中",example:"De lijn is in gesprek."},{nl:"het telefoonnummer",zh:"電話號碼",example:"Wat is uw telefoonnummer?"}],dialogue:{context:"你打電話給學校說小孩生病",lines:[{speaker:"School",text:"Basisschool De Regenboog, goedemorgen."},{speaker:"Jij",text:"Goedemorgen, u spreekt met Chen. Mijn zoon is ziek."},{speaker:"School",text:"Wat vervelend. In welke klas zit hij?"},{speaker:"Jij",text:"In groep vijf, bij juf Marieke."},{speaker:"School",text:"Oké, ik geef het door. Beterschap!"},{speaker:"Jij",text:"Dank u wel. Dag!"}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"我可以留言嗎？",answer:"Kan ik een boodschap achterlaten?"},{zh:"你可以回電給我嗎？",answer:"Kunt u mij terugbellen?"},{zh:"我兒子生病了。",answer:"Mijn zoon is ziek."}]},speaking:"Spreken 模擬：假裝打電話取消預約。說名字、預約時間、原因。錄音 30 秒。",listening:"YouTube 搜尋「telefoneren Nederlands A2」看影片。",goldenSentence:"U spreekt met Chen. Mijn zoon is ziek vandaag.",goldenSentenceZh:"我是 Chen。我兒子今天生病了。",examFocus:"spreken"},
  11:{theme:"Het weer",themeZh:"天氣",vocab:[{nl:"het weer",zh:"天氣",example:"Het weer is mooi vandaag."},{nl:"regenen",zh:"下雨",example:"Het regent de hele dag."},{nl:"de paraplu",zh:"雨傘",example:"Vergeet je paraplu niet!"},{nl:"de jas",zh:"外套",example:"Trek een warme jas aan."},{nl:"bewolkt",zh:"多雲",example:"Het is bewolkt maar droog."}],dialogue:{context:"你跟同事聊天氣",lines:[{speaker:"Collega",text:"Wat een weer, hè? Het regent al de hele ochtend."},{speaker:"Jij",text:"Ja, ik ben helemaal nat geworden op de fiets."},{speaker:"Collega",text:"Morgen wordt het beter. Zon en achttien graden."},{speaker:"Jij",text:"Fijn! Dan ga ik een stukje wandelen."},{speaker:"Collega",text:"Goed idee. Neem toch je jas mee."},{speaker:"Jij",text:"Ja, dit is Nederland. Je weet het nooit!"}]},exercise:{instruction:"翻譯成荷蘭文：",questions:[{zh:"今天天氣很好。",answer:"Het weer is mooi vandaag."},{zh:"別忘了帶雨傘！",answer:"Vergeet je paraplu niet!"},{zh:"一整天都在下雨。",answer:"Het regent de hele dag."}]},speaking:"錄音唸三遍：「Het regent al de hele ochtend.」\n\n發音重點：'regent' 和 'ochtend' 的 g/ch 喉音。",listening:"YouTube 搜尋「het weer Nederlands」看天氣預報影片。",goldenSentence:"Dit is Nederland. Je weet het nooit!",goldenSentenceZh:"這是荷蘭，你永遠不知道天氣會怎樣！",examFocus:"luisteren"},
  12:{theme:"Weekherhaling 2",themeZh:"第二週複習",vocab:[{nl:"de vooruitgang",zh:"進步",example:"Je maakt goede vooruitgang!"},{nl:"moeilijk",zh:"困難",example:"Nederlands is soms moeilijk."},{nl:"makkelijk",zh:"簡單",example:"Dit woord is makkelijk."},{nl:"vergeten",zh:"忘記",example:"Ik ben het woord vergeten."},{nl:"de uitspraak",zh:"發音",example:"Mijn uitspraak moet beter."}],dialogue:{context:"綜合複習 Week 2",lines:[{speaker:"Vriend",text:"Hoe gaat het met je nieuwe huis?"},{speaker:"Jij",text:"Goed! De huur is redelijk en de buren zijn aardig."},{speaker:"Vriend",text:"Heb je al een bankrekening geopend?"},{speaker:"Jij",text:"Ja, ik heb nu ook internetbankieren."},{speaker:"Vriend",text:"Zullen we vanavond uit eten gaan?"},{speaker:"Jij",text:"Ja leuk! Ik wil dat nieuwe restaurant proberen."}]},exercise:{instruction:"Week 2 綜合測驗：",questions:[{zh:"我想預約看房。",answer:"Ik wil een bezichtiging plannen."},{zh:"帳單請給我。",answer:"Mag ik de rekening, alstublieft?"},{zh:"明天天氣會比較好。",answer:"Morgen wordt het weer beter."}]},speaking:"Schrijven 模擬：用荷蘭文寫短信邀請朋友週六吃飯。",listening:"回顧 Week 2，挑最弱的情境再看一次影片。",goldenSentence:"Je maakt goede vooruitgang!",goldenSentenceZh:"你進步很大！",examFocus:"schrijven"},
  13:{theme:"Werkwoorden (tegenwoordige tijd)",themeZh:"動詞（現在式）",vocab:[{nl:"werken — ik werk, jij werkt, hij werkt, wij werken",zh:"工作",example:"Ik werk in een winkel."},{nl:"wonen — ik woon, jij woont, hij woont, wij wonen",zh:"住",example:"Wij wonen in Lelystad."},{nl:"hebben — ik heb, jij hebt, hij heeft, wij hebben",zh:"有",example:"Zij heeft twee kinderen."},{nl:"zijn — ik ben, jij bent, hij is, wij zijn",zh:"是",example:"Wij zijn blij."},{nl:"kunnen — ik kan, jij kunt, hij kan, wij kunnen",zh:"能/可以",example:"Ik kan een beetje Nederlands spreken."}],dialogue:{context:"用正確的動詞形式填空",lines:[{speaker:"Vraag",text:"Waar _____ (wonen) jij?"},{speaker:"Antwoord",text:"Ik woon in Lelystad."},{speaker:"Vraag",text:"Wat _____ (doen) je vrouw?"},{speaker:"Antwoord",text:"Zij werkt in een ziekenhuis."},{speaker:"Vraag",text:"_____ (hebben) jullie kinderen?"},{speaker:"Antwoord",text:"Ja, wij hebben één zoon."}]},exercise:{instruction:"選擇正確的動詞形式：",questions:[{zh:"Hij _____ (werken) bij een bank.",answer:"Hij werkt bij een bank."},{zh:"Wij _____ (zijn) uit Taiwan.",answer:"Wij zijn uit Taiwan."},{zh:"_____ (kunnen) jij morgen komen?",answer:"Kun jij morgen komen?"}]},speaking:"錄音：用 5 句描述日常生活，每句不同動詞。",listening:"YouTube 搜尋「dagelijks leven Nederlands A2」聽別人描述日常。",goldenSentence:"Ik kan een beetje Nederlands spreken.",goldenSentenceZh:"我會說一點荷蘭文。",examFocus:"schrijven"},
  14:{theme:"Verleden tijd (perfectum)",themeZh:"過去式（完成式）",vocab:[{nl:"hebben + ge___d/t",zh:"弱動詞過去分詞",example:"Ik heb gewerkt."},{nl:"zijn + ge___en",zh:"強動詞（移動/狀態變化）",example:"Ik ben gegaan."},{nl:"gekocht",zh:"買了",example:"Ik heb een jas gekocht."},{nl:"geweest",zh:"去過/是過",example:"Ik ben in Amsterdam geweest."},{nl:"gedaan",zh:"做了",example:"Wat heb je gisteren gedaan?"}],dialogue:{context:"聊你昨天做了什麼",lines:[{speaker:"Vriend",text:"Wat heb je gisteren gedaan?"},{speaker:"Jij",text:"Ik ben naar de markt gegaan."},{speaker:"Vriend",text:"Heb je iets gekocht?"},{speaker:"Jij",text:"Ja, ik heb groente en fruit gekocht."},{speaker:"Vriend",text:"Heb je ook gekookt?"},{speaker:"Jij",text:"Ja, ik heb een lekkere soep gemaakt."}]},exercise:{instruction:"用完成式改寫：",questions:[{zh:"Ik ga naar school. → (gisteren)",answer:"Ik ben naar school gegaan."},{zh:"Zij koopt een boek. → (vorige week)",answer:"Zij heeft een boek gekocht."},{zh:"Wij eten bij een restaurant. → (gisteren)",answer:"Wij hebben bij een restaurant gegeten."}]},speaking:"用過去式說 3 件你昨天做的事。錄音。",listening:"YouTube 搜尋「perfectum Nederlands A2」看文法教學。",goldenSentence:"Wat heb je gisteren gedaan?",goldenSentenceZh:"你昨天做了什麼？",examFocus:"spreken"},
  15:{theme:"Woordvolgorde",themeZh:"語序規則",vocab:[{nl:"Hoofdzin: S + V + ...",zh:"主句：主詞+動詞+其他",example:"Ik ga morgen naar Amsterdam."},{nl:"Inversie: X + V + S",zh:"倒裝：時間/地點開頭",example:"Morgen ga ik naar Amsterdam."},{nl:"Bijzin: ...S...V(最後)",zh:"子句：動詞放最後",example:"...omdat ik ziek ben."},{nl:"omdat",zh:"因為（子句）",example:"Ik kom niet, omdat ik ziek ben."},{nl:"wanneer",zh:"當...的時候",example:"Wanneer ik thuis ben, kook ik."}],dialogue:{context:"練習語序變化",lines:[{speaker:"正常",text:"Ik ga morgen naar de dokter."},{speaker:"倒裝",text:"Morgen ga ik naar de dokter."},{speaker:"正常",text:"Ik kan niet komen."},{speaker:"+原因",text:"Ik kan niet komen, omdat ik moet werken."},{speaker:"正常",text:"Ik bel je op."},{speaker:"+時間",text:"Wanneer ik thuis ben, bel ik je op."}]},exercise:{instruction:"修正語序：",questions:[{zh:"Gisteren ik ben naar school gegaan. →",answer:"Gisteren ben ik naar school gegaan."},{zh:"Ik kom niet, omdat ik ben ziek. →",answer:"Ik kom niet, omdat ik ziek ben."},{zh:"Volgende week ik ga naar Brussel. →",answer:"Volgende week ga ik naar Brussel."}]},speaking:"用「Morgen ga ik...」開頭說 3 個明天計畫。注意倒裝！錄音。",listening:"YouTube 搜尋「woordvolgorde Nederlands」看文法教學。",goldenSentence:"Morgen ga ik naar Amsterdam, omdat ik een afspraak heb.",goldenSentenceZh:"明天我去阿姆斯特丹，因為我有預約。",examFocus:"schrijven"},
  16:{theme:"Voegwoorden",themeZh:"連接詞",vocab:[{nl:"en / maar / want",zh:"和/但是/因為（不影響語序）",example:"Het regent, maar ik ga toch."},{nl:"omdat / als / wanneer",zh:"因為/如果/當（動詞放最後）",example:"...omdat ik ziek ben."},{nl:"want vs omdat",zh:"都是「因為」但語序不同！",example:"Ik blijf thuis, want ik ben ziek. ≠ ...omdat ik ziek ben."},{nl:"als",zh:"如果（子句）",example:"Als het regent, neem ik de bus."},{nl:"dat",zh:"that（子句）",example:"Ik denk dat hij ziek is."}],dialogue:{context:"注意 want vs omdat 的語序差別",lines:[{speaker:"want",text:"Ik ga niet, want ik heb geen tijd. (語序不變)"},{speaker:"omdat",text:"Ik ga niet, omdat ik geen tijd heb. (動詞最後)"},{speaker:"maar",text:"Ik ben moe, maar ik ga toch."},{speaker:"als",text:"Als ik vrij ben, ga ik naar het park."},{speaker:"dat",text:"Ik denk dat het morgen regent."},{speaker:"omdat",text:"Ik leer Nederlands, omdat ik in Nederland woon."}]},exercise:{instruction:"用 want 或 omdat 連接：",questions:[{zh:"Ik ga vroeg naar bed + Ik ben moe (want)",answer:"Ik ga vroeg naar bed, want ik ben moe."},{zh:"Ik ga vroeg naar bed + Ik ben moe (omdat)",answer:"Ik ga vroeg naar bed, omdat ik moe ben."},{zh:"如果天氣好，我騎腳踏車。",answer:"Als het weer mooi is, ga ik met de fiets."}]},speaking:"用 omdat 說 3 個你學荷蘭文的原因。錄音。",listening:"YouTube 搜尋「voegwoorden Nederlands A2」看文法教學。",goldenSentence:"Ik leer Nederlands, omdat ik in Nederland woon.",goldenSentenceZh:"我學荷蘭文，因為我住在荷蘭。",examFocus:"schrijven"},
  17:{theme:"Er & het gebruik",themeZh:"er 的用法",vocab:[{nl:"er is / er zijn",zh:"有（存在）",example:"Er is een supermarkt in de buurt."},{nl:"er + 數字",zh:"代替數量",example:"Ik heb er drie."},{nl:"ernaartoe",zh:"去那裡",example:"Ik ga er morgen naartoe."},{nl:"erover",zh:"關於那個",example:"We praten erover."},{nl:"het is + weer/tijd",zh:"虛主詞 het",example:"Het is koud vandaag."}],dialogue:{context:"練習 er 的各種用法",lines:[{speaker:"Vraag",text:"Is er een apotheek in de buurt?"},{speaker:"Antwoord",text:"Ja, er is er een op de hoek."},{speaker:"Vraag",text:"Hoeveel kinderen heb je?"},{speaker:"Antwoord",text:"Ik heb er twee."},{speaker:"Vraag",text:"Ben je al naar het gemeentehuis geweest?"},{speaker:"Antwoord",text:"Nee, ik ga er morgen naartoe."}]},exercise:{instruction:"用 er 填空：",questions:[{zh:"_____ zijn veel winkels in het centrum.",answer:"Er zijn veel winkels in het centrum."},{zh:"Hoeveel broers heb je? — Ik heb _____ drie.",answer:"Ik heb er drie."},{zh:"_____ is koud vandaag.",answer:"Het is koud vandaag."}]},speaking:"用 er is/er zijn 描述你家附近有什麼。錄音 30 秒。",listening:"YouTube 搜尋「er Nederlands grammatica」看教學。",goldenSentence:"Er is een supermarkt in de buurt.",goldenSentenceZh:"附近有一間超市。",examFocus:"lezen"},
  18:{theme:"Grammatica herhaling",themeZh:"文法總複習",vocab:[{nl:"de werkwoordstijden",zh:"動詞時態",example:"Ken je alle werkwoordstijden?"},{nl:"de bijzin",zh:"子句",example:"In een bijzin staat het werkwoord achteraan."},{nl:"de inversie",zh:"倒裝",example:"Bij inversie: werkwoord op plek twee."},{nl:"het hulpwerkwoord",zh:"助動詞",example:"Kunnen, moeten, willen."},{nl:"het voltooid deelwoord",zh:"過去分詞",example:"gegaan, gewerkt, gekocht"}],dialogue:{context:"文法綜合練習",lines:[{speaker:"現在",text:"Ik ga morgen naar de huisarts."},{speaker:"過去",text:"Ik ben gisteren naar de huisarts gegaan."},{speaker:"+omdat",text:"...omdat ik ziek was."},{speaker:"倒裝",text:"Gisteren ben ik naar de huisarts gegaan."},{speaker:"+als",text:"Als ik ziek ben, ga ik naar de huisarts."},{speaker:"+er",text:"Er is een huisarts in mijn buurt."}]},exercise:{instruction:"文法總測驗：",questions:[{zh:"改成過去式：Ik koop een boek.",answer:"Ik heb een boek gekocht."},{zh:"加 omdat：Ik ga niet + ik heb geen tijd",answer:"Ik ga niet, omdat ik geen tijd heb."},{zh:"倒裝：Volgende maand / ik / verhuizen / naar Amsterdam",answer:"Volgende maand verhuis ik naar Amsterdam."}]},speaking:"用荷蘭文講你上週末做了什麼（過去式）。至少 5 句，錄音。",listening:"回顧 Week 3，把不懂的文法再看一次教學影片。",goldenSentence:"In een bijzin staat het werkwoord achteraan.",goldenSentenceZh:"在子句中動詞放在最後。",examFocus:"schrijven"},
  19:{theme:"KNM: Gezondheid",themeZh:"KNM：醫療與保險",vocab:[{nl:"de zorgverzekering",zh:"健保",example:"Iedereen moet een zorgverzekering hebben."},{nl:"het eigen risico",zh:"自付額",example:"Het eigen risico is 385 euro per jaar."},{nl:"de huisarts (poortwachter)",zh:"家庭醫生（守門人）",example:"Je gaat eerst naar de huisarts."},{nl:"de specialist",zh:"專科醫生",example:"De huisarts verwijst je naar een specialist."},{nl:"112 bellen",zh:"打緊急電話",example:"Bij nood bel je 112."}],dialogue:{context:"KNM 醫療知識問答",lines:[{speaker:"Q",text:"Wat moet iedereen in Nederland hebben?"},{speaker:"A",text:"Een zorgverzekering."},{speaker:"Q",text:"Waar ga je eerst naartoe als je ziek bent?"},{speaker:"A",text:"Naar de huisarts."},{speaker:"Q",text:"Welk nummer bel je bij nood?"},{speaker:"A",text:"112."}]},exercise:{instruction:"KNM 模擬題：",questions:[{zh:"生病時先去找誰？",answer:"De huisarts. 荷蘭以 huisarts 為守門人，需轉介才能看 specialist。"},{zh:"每個人必須有什麼保險？",answer:"Zorgverzekering（基本健保）。每年 1 月可換保險公司。"},{zh:"緊急電話？非緊急警察電話？",answer:"緊急：112。非緊急：0900-8844。"}]},speaking:"用荷蘭文解釋荷蘭醫療系統。錄音。",listening:"YouTube 搜尋「KNM gezondheid inburgering」看教學。",goldenSentence:"In Nederland moet iedereen een zorgverzekering hebben.",goldenSentenceZh:"在荷蘭每個人都必須有健保。",examFocus:"knm"},
  20:{theme:"KNM: Onderwijs",themeZh:"KNM：教育",vocab:[{nl:"de leerplicht",zh:"義務教育",example:"Kinderen van 5 tot 18 jaar hebben leerplicht."},{nl:"de basisschool",zh:"小學",example:"Groep 1 tot 8."},{nl:"het voortgezet onderwijs",zh:"中學",example:"VMBO, HAVO, VWO."},{nl:"de Cito-toets",zh:"Cito 測驗",example:"In groep 8 maken kinderen de Cito-toets."},{nl:"kinderopvang",zh:"托兒所",example:"Veel ouders gebruiken kinderopvang."}],dialogue:{context:"KNM 教育知識",lines:[{speaker:"Q",text:"Vanaf welke leeftijd moeten kinderen naar school?"},{speaker:"A",text:"Vanaf 5 jaar (meeste gaan al met 4)."},{speaker:"Q",text:"Hoeveel groepen heeft de basisschool?"},{speaker:"A",text:"8 groepen."},{speaker:"Q",text:"Welke soorten middelbare school zijn er?"},{speaker:"A",text:"VMBO (4jr), HAVO (5jr), VWO (6jr)."}]},exercise:{instruction:"KNM 模擬題：",questions:[{zh:"義務教育幾歲到幾歲？",answer:"5 tot 18 jaar."},{zh:"小學有幾個年級？",answer:"8 groepen (groep 1-8)。"},{zh:"中學有哪幾種？",answer:"VMBO (4年), HAVO (5年), VWO (6年，可上大學)。"}]},speaking:"用荷蘭文說你/孩子的教育情況。錄音。",listening:"YouTube 搜尋「onderwijs Nederland KNM」看教學。",goldenSentence:"Kinderen van 5 tot 18 jaar hebben leerplicht.",goldenSentenceZh:"5到18歲有義務教育。",examFocus:"knm"},
  21:{theme:"KNM: Overheid & Wonen",themeZh:"KNM：政府與住房",vocab:[{nl:"de Tweede Kamer",zh:"國會下議院",example:"De Tweede Kamer maakt de wetten."},{nl:"stemmen",zh:"投票",example:"Bij verkiezingen mag je stemmen."},{nl:"sociale huurwoning",zh:"社會住宅",example:"Inschrijven bij Woningnet."},{nl:"de belasting",zh:"稅",example:"Iedereen moet belasting betalen."},{nl:"de gemeente",zh:"市政府",example:"De gemeente regelt veel zaken."}],dialogue:{context:"KNM 政府知識",lines:[{speaker:"Q",text:"Wie is het staatshoofd?"},{speaker:"A",text:"De Koning (Willem-Alexander)."},{speaker:"Q",text:"Wie maakt de wetten?"},{speaker:"A",text:"De Eerste en Tweede Kamer."},{speaker:"Q",text:"Hoe vind je een sociale huurwoning?"},{speaker:"A",text:"Via Woningnet. Lange wachttijd."}]},exercise:{instruction:"KNM 模擬題：",questions:[{zh:"國家元首？政府首腦？",answer:"Staatshoofd: de Koning. Regeringsleider: de minister-president."},{zh:"社會住宅去哪登記？",answer:"Woningnet 或 woningcorporatie。等候時間很長。"},{zh:"什麼時候要聯繫 gemeente？",answer:"搬家登記、申請護照、出生登記、結婚等。"}]},speaking:"用荷蘭文描述你住的房子。錄音。",listening:"YouTube 搜尋「overheid Nederland KNM」看教學。",goldenSentence:"De Tweede Kamer maakt de wetten.",goldenSentenceZh:"國會下議院制定法律。",examFocus:"knm"},
  22:{theme:"Oefenexamen Lezen",themeZh:"閱讀模擬考",vocab:[{nl:"het bericht",zh:"訊息/通知",example:"Lees het bericht."},{nl:"de advertentie",zh:"廣告",example:"In de advertentie staat de prijs."},{nl:"de brief",zh:"信",example:"Een brief van de gemeente."},{nl:"het schema",zh:"時刻表",example:"Kijk op het schema."},{nl:"de instructie",zh:"說明",example:"Lees de instructie."}],dialogue:{context:"閱讀練習：讀通知，回答問題",lines:[{speaker:"Brief",text:"Beste bewoner, op maandag 20 januari is er geen water van 9:00 tot 15:00."},{speaker:"Brief",text:"Dit is nodig voor reparatie aan de waterleiding."},{speaker:"Brief",text:"Zorg dat u genoeg water heeft voor de dag."},{speaker:"Q1",text:"Wanneer is er geen water?"},{speaker:"Q2",text:"Waarom?"},{speaker:"Q3",text:"Wat moet je doen?"}]},exercise:{instruction:"回答閱讀題：",questions:[{zh:"Wanneer is er geen water?",answer:"Maandag 20 januari, 9:00-15:00."},{zh:"Waarom?",answer:"Reparatie aan de waterleiding."},{zh:"Wat moet je doen?",answer:"Genoeg water bewaren voor de dag."}]},speaking:"朗讀上面的 brief，注意語調。錄音。",listening:"去 inburgeren.nl 做官方 Lezen 模擬考。",goldenSentence:"Lees altijd de brief van de gemeente goed!",goldenSentenceZh:"一定要仔細讀市政廳的信！",examFocus:"lezen"},
  23:{theme:"Oefenexamen Luisteren",themeZh:"聽力模擬考",vocab:[{nl:"het gesprek",zh:"對話",example:"Luister naar het gesprek."},{nl:"de omroep",zh:"廣播",example:"Luister naar de omroep."},{nl:"herhalen",zh:"重複",example:"U hoort het fragment twee keer."},{nl:"het fragment",zh:"片段",example:"Luister naar het fragment."},{nl:"het juiste antwoord",zh:"正確答案",example:"Kies het juiste antwoord."}],dialogue:{context:"聽力考試技巧",lines:[{speaker:"Tip 1",text:"聽之前先讀題目。"},{speaker:"Tip 2",text:"注意數字、時間、地點。"},{speaker:"Tip 3",text:"第一遍聽大意，第二遍找細節。"},{speaker:"Tip 4",text:"不懂的詞跳過，抓關鍵字。"},{speaker:"Tip 5",text:"每段音檔聽 1-2 次。"},{speaker:"Tip 6",text:"平時多聽 NOS Journaal 練耳朵。"}]},exercise:{instruction:"做完官方模擬考後回答：",questions:[{zh:"最難的部分是什麼？",answer:"（自由回答——常見：語速快、口音、數字）"},{zh:"答對幾題？",answer:"（記錄分數，追蹤進步）"},{zh:"寫下 3 個聽不懂的詞。",answer:"（查字典，加到單字本）"}]},speaking:"聽完模擬考後，用荷蘭文複述一段對話。錄音。",listening:"去 inburgeren.nl 做官方 Luisteren 模擬考！",goldenSentence:"Luister goed en kies het juiste antwoord.",goldenSentenceZh:"仔細聽，選正確答案。",examFocus:"luisteren"},
  24:{theme:"Oefenexamen Schrijven",themeZh:"寫作模擬考",vocab:[{nl:"Beste / Geachte",zh:"親愛的/尊敬的",example:"Beste mevrouw De Vries,"},{nl:"Met vriendelijke groet",zh:"此致敬意",example:"正式信結尾"},{nl:"Groetjes",zh:"親切問候",example:"非正式信結尾"},{nl:"invullen",zh:"填寫",example:"Vul het formulier in."},{nl:"de reden",zh:"原因",example:"Wat is de reden?"}],dialogue:{context:"寫作考試：40分鐘，4題，紙筆",lines:[{speaker:"Type 1",text:"填表格"},{speaker:"Type 2",text:"寫短信（請假、改預約）"},{speaker:"Type 3",text:"回覆邀請或通知"},{speaker:"Type 4",text:"寫信解釋情況或請求"},{speaker:"重點",text:"傳達訊息最重要，文法不完美沒關係。"},{speaker:"時間",text:"每題約 10 分鐘。"}]},exercise:{instruction:"寫作模擬（用紙筆！）：",questions:[{zh:"寫信給學校：孩子明天生病不來。",answer:"Beste juf, Mijn zoon kan morgen niet naar school komen. Hij is ziek en heeft koorts. Ik hoop dat hij overmorgen weer kan komen. Met vriendelijke groet, Chen"},{zh:"回覆鄰居派對邀請：你可以來，問帶什麼。",answer:"Hoi Maria, Bedankt voor de uitnodiging! Ik kom graag zaterdag. Zal ik iets te eten meenemen? Groetjes, Chen"},{zh:"寫信給房東：暖氣壞了，請他修。",answer:"Geachte heer, De verwarming in mijn woning werkt niet. Het is al drie dagen koud. Kunt u iemand sturen om het te repareren? Met vriendelijke groet, Chen"}]},speaking:"朗讀你寫的信件。錄音。",listening:"去 inburgeren.nl 做官方 Schrijven 模擬考。",goldenSentence:"Beste mevrouw, ik schrijf u omdat...",goldenSentenceZh:"女士您好，我寫信是因為...",examFocus:"schrijven"},
  25:{theme:"Oefenexamen Spreken",themeZh:"口說模擬考",vocab:[{nl:"de microfoon",zh:"麥克風",example:"Spreek in de microfoon."},{nl:"de afbeelding",zh:"圖片",example:"Beschrijf de afbeelding."},{nl:"beschrijven",zh:"描述",example:"Beschrijf wat je ziet."},{nl:"de pieptoon",zh:"嗶聲",example:"Begin na de pieptoon."},{nl:"Op deze afbeelding zie ik...",zh:"在這張圖中我看到...",example:"萬用開頭句"}],dialogue:{context:"口說考試：35分鐘，對電腦錄音，全部口說（無選擇題）",lines:[{speaker:"Deel 1",text:"看影片回答問題"},{speaker:"Deel 2",text:"看 1 張圖，描述情境"},{speaker:"Deel 3",text:"看 2 張圖，比較或講故事"},{speaker:"Deel 4",text:"看 3 張圖，講完整故事"},{speaker:"策略",text:"每題約 1 分鐘。短句清楚最重要。"},{speaker:"萬用句",text:"Op deze afbeelding zie ik... Ik denk dat... Links/rechts staat..."}]},exercise:{instruction:"口說模擬（每題錄音 1 分鐘）：",questions:[{zh:"描述你的家。",answer:"結構：Ik woon in... Het heeft... De keuken is... Ik vind... het leukst."},{zh:"你最喜歡的食物，怎麼做？",answer:"結構：Mijn lievelingseten is... Ik maak het met... Eerst... Dan..."},{zh:"描述你上週去過的地方。",answer:"結構：Vorige week ben ik naar... gegaan. Ik heb daar... Het was..."}]},speaking:"去 inburgeren.nl 做官方 Spreken 模擬考！\n\n萬用句：\n• Op deze afbeelding zie ik...\n• Ik denk dat...\n• Links/rechts staat...",listening:"YouTube 搜尋「spreken inburgering A2」看別人怎麼回答。",goldenSentence:"Op deze afbeelding zie ik een vrouw die boodschappen doet.",goldenSentenceZh:"在這張圖中我看到一個在買菜的女人。",examFocus:"spreken"},
  26:{theme:"KNM: Werk & Normen",themeZh:"KNM：工作與規範",vocab:[{nl:"het arbeidscontract",zh:"勞動合約",example:"Lees je contract goed."},{nl:"het minimumloon",zh:"最低工資",example:"Nederland heeft een minimumloon."},{nl:"gelijke behandeling",zh:"平等對待",example:"Gelijke behandeling is belangrijk."},{nl:"discriminatie",zh:"歧視",example:"Discriminatie is verboden."},{nl:"op tijd komen",zh:"準時",example:"Nederlanders vinden op tijd komen belangrijk."}],dialogue:{context:"KNM 工作與荷蘭價值觀",lines:[{speaker:"Q",text:"Is discriminatie toegestaan?"},{speaker:"A",text:"Nee, discriminatie is verboden."},{speaker:"Q",text:"Wat is belangrijk in de Nederlandse cultuur?"},{speaker:"A",text:"Directheid, op tijd komen, gelijkheid, tolerantie."},{speaker:"Q",text:"Wat staat er in een arbeidscontract?"},{speaker:"A",text:"Werk, uren, salaris, vakantiedagen."}]},exercise:{instruction:"KNM 模擬題：",questions:[{zh:"合約裡應該有什麼？",answer:"工作內容、工時、薪水、試用期、假期天數。"},{zh:"荷蘭重要的社會價值？",answer:"Gelijkheid, vrijheid, tolerantie, directheid, op tijd komen."},{zh:"被歧視找誰？",answer:"College voor de Rechten van de Mens 或 antidiscriminatiebureau。"}]},speaking:"用荷蘭文說你的工作經驗。錄音。",listening:"YouTube 搜尋「werk Nederland KNM」看教學。",goldenSentence:"In Nederland is gelijke behandeling heel belangrijk.",goldenSentenceZh:"在荷蘭，平等對待非常重要。",examFocus:"knm"},
  27:{theme:"Gecombineerd oefenexamen 1",themeZh:"綜合模擬考 1",vocab:[{nl:"slagen",zh:"及格",example:"Ik wil slagen!"},{nl:"zakken",zh:"不及格",example:"Als je zakt, kun je herkansen."},{nl:"de uitslag",zh:"成績",example:"De uitslag komt binnen 8 weken."},{nl:"de herkansing",zh:"補考",example:"Je kunt een herkansing doen."},{nl:"het examen",zh:"考試",example:"Het examen is volgende week."}],dialogue:{context:"考試資訊提醒",lines:[{speaker:"📌",text:"每科可以分開不同天考。"},{speaker:"📌",text:"考前 15 分鐘 instructie。"},{speaker:"📌",text:"Schrijven 紙筆，其他電腦。"},{speaker:"📌",text:"Spreken 對電腦錄音，沒有真人。"},{speaker:"📌",text:"不及格只重考那一科。"},{speaker:"📌",text:"通過的科目永久有效。"}]},exercise:{instruction:"綜合練習：",questions:[{zh:"【Lezen】Aanbieding: kaas €3,99/kg, alleen deze week. 特價到何時？",answer:"Alleen deze week (只有這週)。"},{zh:"【Schrijven】寫信取消明天的醫生預約，因為出差。",answer:"Geachte dokter, Ik wil mijn afspraak van morgen annuleren, omdat ik op zakenreis moet. Kan ik een nieuwe afspraak maken? Met vriendelijke groet, Chen"},{zh:"【KNM】緊急電話號碼？",answer:"112"}]},speaking:"看窗外景象，用荷蘭文描述 1 分鐘。用 er is/er zijn, links/rechts。錄音。",listening:"去 inburgeren.nl 做還沒做過的官方模擬考。",goldenSentence:"Ik ga voor alle onderdelen slagen!",goldenSentenceZh:"我每一科都要通過！",examFocus:"lezen"},
  28:{theme:"Gecombineerd oefenexamen 2",themeZh:"綜合模擬考 2",vocab:[{nl:"zelfverzekerd",zh:"有自信",example:"Wees zelfverzekerd!"},{nl:"rustig",zh:"冷靜",example:"Blijf rustig."},{nl:"de tijd",zh:"時間",example:"Let op de tijd!"},{nl:"de vraag",zh:"問題",example:"Lees elke vraag twee keer."},{nl:"het woordenboek",zh:"字典",example:"Bij Spreken: geen woordenboek."}],dialogue:{context:"考試策略",lines:[{speaker:"Lezen",text:"先掃題目再讀文章。65分鐘。"},{speaker:"Luisteren",text:"聽前先讀選項。注意數字時間。"},{speaker:"Schrijven",text:"每題10分鐘。寫完檢查拼字。"},{speaker:"Spreken",text:"嗶聲後馬上說。用簡單短句。"},{speaker:"KNM",text:"40題45分鐘。不確定先跳過。"},{speaker:"全部",text:"先考最有把握的科目！"}]},exercise:{instruction:"最後衝刺：",questions:[{zh:"【Spreken】鄰居太吵，描述情況和感受。",answer:"Mijn buren maken veel lawaai 's avonds. Ik kan niet slapen. Ik wil met ze praten."},{zh:"【KNM】幾歲可以喝酒？",answer:"18 jaar."},{zh:"【Schrijven】填寫：Naam, Adres, Geboortedatum, Reden van bezoek",answer:"（用你真實資料練習填寫）"}]},speaking:"完整 Spreken 模擬：4 題，每題 1 分鐘。計時！",listening:"最後一次做 inburgeren.nl 聽力模擬考。記下分數。",goldenSentence:"Blijf rustig en doe je best. Je kunt het!",goldenSentenceZh:"保持冷靜，盡力而為。你可以的！",examFocus:"spreken"},
  29:{theme:"Totale herhaling",themeZh:"總複習",vocab:[{nl:"trots",zh:"驕傲",example:"Ik ben trots op mijn vooruitgang!"},{nl:"klaar",zh:"準備好了",example:"Ik ben klaar!"},{nl:"doorgaan",zh:"繼續",example:"Na A2 ga ik door met B1."},{nl:"bedanken",zh:"感謝",example:"Ik wil je bedanken."},{nl:"het resultaat",zh:"結果",example:"Het resultaat komt over 8 weken."}],dialogue:{context:"最後複習清單",lines:[{speaker:"✅",text:"10 個生活情境對話（Week 1-2）"},{speaker:"✅",text:"動詞現在式和過去式（Week 3）"},{speaker:"✅",text:"語序：倒裝、子句（Week 3）"},{speaker:"✅",text:"KNM：醫療、教育、住房、政府、工作"},{speaker:"✅",text:"5 科模擬考都做過了"},{speaker:"✅",text:"150+ 個 A2 核心單字"}]},exercise:{instruction:"自我評估（1-5分）：",questions:[{zh:"Lezen：能讀懂超市傳單、gemeente 的信嗎？",answer:"目標 3+ 分才去考。不到多做模擬題。"},{zh:"Spreken：能用簡單句描述日常嗎？",answer:"目標 3+ 分。多錄音，聽自己的錯。"},{zh:"Schrijven：能寫簡單信件和填表嗎？",answer:"目標 3+ 分。記住信件格式。"}]},speaking:"用荷蘭文講 2 分鐘：這 30 天學了什麼、你的感受。錄音保存！",listening:"重做分數最低的那科模擬考。",goldenSentence:"Ik ben klaar voor het examen!",goldenSentenceZh:"我準備好考試了！",examFocus:"spreken"},
  30:{theme:"Examendag!",themeZh:"考試日！",vocab:[{nl:"Succes!",zh:"祝你成功！",example:"Succes met je examen!"},{nl:"Je kunt het!",zh:"你可以的！",example:"Geloof in jezelf."},{nl:"Goed gedaan!",zh:"做得好！",example:"Goed gedaan!"},{nl:"Gefeliciteerd!",zh:"恭喜！",example:"Gefeliciteerd met je diploma!"},{nl:"doorgaan",zh:"繼續前進",example:"Nu ga ik door met B1!"}],dialogue:{context:"考試日提醒",lines:[{speaker:"📌",text:"帶身份證件（ID/護照）"},{speaker:"📌",text:"提前 15 分鐘到"},{speaker:"📌",text:"Schrijven：帶自己的筆"},{speaker:"📌",text:"放輕鬆，你準備了 30 天"},{speaker:"📌",text:"不及格可以補考，只補那一科"},{speaker:"📌",text:"8 週內收到成績"}]},exercise:{instruction:"你完成了 30 天準備！",questions:[{zh:"寫 3 個你最有信心的單字。",answer:"（給自己信心！）"},{zh:"1 個考前最想複習的文法。",answer:"（複習它，然後放下！）"},{zh:"用荷蘭文鼓勵自己。",answer:"Ik heb hard gewerkt en ik ben klaar!"}]},speaking:"對鏡子用荷蘭文自我介紹 1 分鐘。微笑，深呼吸！",listening:"今天不用做聽力。休息，放鬆，早點睡。",goldenSentence:"Ik heb hard gewerkt en ik ben klaar!",goldenSentenceZh:"我努力準備了，我已經準備好了！",examFocus:"spreken"},
};

const WEEK_PLAN = [
  { week: 1, title: "生活核心情境（上）", days: [1,2,3,4,5,6,null] },
  { week: 2, title: "生活核心情境（下）", days: [7,8,9,10,11,12,null] },
  { week: 3, title: "A2 文法重點", days: [13,14,15,16,17,18,null] },
  { week: 4, title: "模擬考 + KNM", days: [19,20,21,22,23,24,25] },
  { week: 5, title: "最後衝刺", days: [26,27,28,29,30,null,null] },
];

const DAY_LABELS = {1:"看醫生",2:"超市",3:"市政廳",4:"火車",5:"鄰居",6:"週複習",7:"餐廳",8:"找房子",9:"銀行",10:"打電話",11:"天氣",12:"週複習",13:"現在式",14:"過去式",15:"語序",16:"連接詞",17:"er用法",18:"文法複習",19:"KNM醫療",20:"KNM教育",21:"KNM政府",22:"閱讀考",23:"聽力考",24:"寫作考",25:"口說考",26:"KNM工作",27:"模擬考1",28:"模擬考2",29:"總複習",30:"考試日！"};

const TABS = ["今日課程", "考試資訊", "課程總覽", "單字本"];

function DutchA2App() {
  const [currentDay, setCurrentDay] = useState(1);
  const [activeTab, setActiveTab] = useState(0);
  const [answers, setAnswers] = useState({});
  const [showAnswers, setShowAnswers] = useState({});
  const [completedDays, setCompletedDays] = useState(new Set());
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const savedDay = localStorage.getItem('dutch_currentDay');
    const savedCompleted = localStorage.getItem('dutch_completedDays');
    if (savedDay) setCurrentDay(Number(savedDay));
    if (savedCompleted) setCompletedDays(new Set(JSON.parse(savedCompleted)));
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    localStorage.setItem('dutch_currentDay', currentDay);
  }, [currentDay, hydrated]);

  const markComplete = () => setCompletedDays(prev => {
    const next = new Set([...prev, currentDay]);
    localStorage.setItem('dutch_completedDays', JSON.stringify([...next]));
    return next;
  });

  if (!hydrated) return <div style={{background:'#0d1117',minHeight:'100vh'}} />;

  const day = COURSE_DATA[currentDay];

  return (
    <div style={S.container}>
      <div style={S.header}>
        <div style={S.headerTop}>
          <div style={S.logo}><span style={{fontSize:26}}>🇳🇱</span><div><div style={S.logoTitle}>Nederlands A2</div><div style={S.logoSub}>Inburgering · 30 Dagen</div></div></div>
        </div>
        <div style={S.tabs}>{TABS.map((t,i)=><button key={i} style={activeTab===i?{...S.tab,...S.tabActive}:S.tab} onClick={()=>setActiveTab(i)}>{t}</button>)}</div>
      </div>

      {activeTab===0 && day && (
        <div style={S.content}>
          <div style={S.dayNav}>
            <button style={{...S.navBtn,opacity:currentDay<=1?.3:1}} onClick={()=>currentDay>1&&setCurrentDay(currentDay-1)}>←</button>
            <div style={{textAlign:"center",display:"flex",flexDirection:"column",gap:2}}>
              <span style={S.dayLabel}>DAG {currentDay}</span>
              <span style={{fontSize:19,fontWeight:800,color:C.text}}>{day.theme}</span>
              <span style={{fontSize:12,color:C.textMuted}}>{day.themeZh}</span>
              {day.examFocus&&<span style={S.examBadge}>{EXAM_INFO[day.examFocus]?.icon} {EXAM_INFO[day.examFocus]?.name}</span>}
            </div>
            <button style={{...S.navBtn,opacity:currentDay>=30?.3:1}} onClick={()=>currentDay<30&&setCurrentDay(currentDay+1)}>→</button>
          </div>

          <Sec icon="📖" title="今日單字" sub="Nieuwe woorden">
            <div style={{display:"flex",flexDirection:"column",gap:6}}>{day.vocab.map((v,i)=>(
              <div key={i} style={S.vocabCard}><div style={S.vocabNl}>{v.nl}</div><div style={{fontSize:12,color:C.textMuted,marginTop:1}}>{v.zh}</div><div style={{fontSize:12,color:C.textDim,marginTop:4,fontStyle:"italic"}}>{v.example}</div></div>
            ))}</div>
          </Sec>

          <Sec icon="💬" title="情境對話" sub="Dialoog">
            <div style={S.ctxBox}>{day.dialogue.context}</div>
            <div style={{display:"flex",flexDirection:"column",gap:5}}>{day.dialogue.lines.map((l,i)=>(
              <div key={i} style={l.speaker==="Jij"?S.dlgYou:S.dlg}><span style={S.dlgSpeaker}>{l.speaker}</span><span style={{fontSize:13,color:C.text,lineHeight:1.5}}>{l.text}</span></div>
            ))}</div>
          </Sec>

          <Sec icon="✏️" title="練習題" sub="Oefening">
            <p style={{fontSize:12,color:C.textMuted,marginBottom:10}}>{day.exercise.instruction}</p>
            {day.exercise.questions.map((q,i)=>{const k=`${currentDay}-${i}`;return(
              <div key={i} style={{marginBottom:14}}>
                <div style={{fontSize:13,fontWeight:600,color:C.text,marginBottom:5}}>{q.zh}</div>
                <textarea style={S.input} placeholder="寫你的答案..." value={answers[k]||""} onChange={e=>setAnswers({...answers,[k]:e.target.value})} rows={2}/>
                <button style={S.btnCheck} onClick={()=>setShowAnswers({...showAnswers,[k]:!showAnswers[k]})}>{showAnswers[k]?"隱藏":"看答案"}</button>
                {showAnswers[k]&&<div style={S.answerBox}>✅ {q.answer}</div>}
              </div>
            );})}
          </Sec>

          <Sec icon="🎙️" title="口說練習" sub="Spreken">
            <div style={S.infoBox}>{day.speaking.split('\n').map((l,i)=><p key={i} style={{margin:l===''?'8px 0':'4px 0'}}>{l}</p>)}</div>
          </Sec>

          <Sec icon="🎧" title="聽力任務" sub="Luisteren">
            <div style={S.infoBox}>{day.listening}</div>
          </Sec>

          <Sec icon="⭐" title="今日金句" sub="Zin van de dag">
            <div style={S.goldenBox}><div style={{fontSize:17,fontWeight:800,color:C.accentText,marginBottom:3}}>{day.goldenSentence}</div><div style={{fontSize:12,color:C.textMuted}}>{day.goldenSentenceZh}</div></div>
          </Sec>

          <div style={{textAlign:"center",padding:"18px 0"}}>
            {completedDays.has(currentDay)?<div style={S.doneBadge}>✅ Goed gedaan!</div>:<button style={S.btnDone} onClick={markComplete}>完成今日課程 ✓</button>}
          </div>
        </div>
      )}

      {activeTab===1&&(
        <div style={S.content}>
          <div style={{textAlign:"center",marginBottom:20}}><h2 style={{fontSize:20,fontWeight:800,color:C.text,margin:0}}>A2 考試全攻略</h2><p style={{fontSize:12,color:C.textMuted,marginTop:4}}>5 個科目，可以分開不同天考</p></div>
          {Object.entries(EXAM_INFO).map(([k,info])=>(
            <div key={k} style={S.examCard}>
              <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:10}}><span style={{fontSize:24}}>{info.icon}</span><div><div style={{fontSize:16,fontWeight:700,color:C.text}}>{info.name}</div><div style={{fontSize:12,color:C.textMuted}}>{info.duration}</div></div></div>
              <div style={{fontSize:13,color:C.text,lineHeight:1.5,marginBottom:8}}><strong>格式：</strong>{info.format}</div>
              <div style={{fontSize:12,color:C.accentText,lineHeight:1.5,padding:"8px 10px",background:C.accentSoft,borderRadius:8}}>💡 {info.tip}</div>
            </div>
          ))}
          <div style={S.examCard}>
            <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:10}}><span style={{fontSize:24}}>💰</span><div><div style={{fontSize:16,fontWeight:700,color:C.text}}>考試費用</div></div></div>
            <div style={{fontSize:13,color:C.text,lineHeight:1.8}}>Lezen €50 · Luisteren €50 · Schrijven €50 · Spreken €60 · KNM €50</div>
            <div style={{fontSize:12,color:C.accentText,padding:"8px 10px",background:C.accentSoft,borderRadius:8,marginTop:8}}>💡 不及格只需重考該科。通過的科目永久有效。成績 8 週內出。</div>
          </div>
          <div style={S.examCard}>
            <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:10}}><span style={{fontSize:24}}>🔗</span><div><div style={{fontSize:16,fontWeight:700,color:C.text}}>官方免費模擬考</div></div></div>
            <div style={{fontSize:13,color:C.text,lineHeight:1.5}}>inburgeren.nl → Examen doen → Oefenen</div>
            <div style={{fontSize:12,color:C.accentText,padding:"8px 10px",background:C.accentSoft,borderRadius:8,marginTop:8}}>💡 每科有 2-3 套模擬考。Spreken 在 Safari 不能用，請用 Chrome。</div>
          </div>
        </div>
      )}

      {activeTab===2&&(
        <div style={S.content}>
          <div style={{textAlign:"center",marginBottom:20}}><h2 style={{fontSize:20,fontWeight:800,color:C.text,margin:0}}>30 天 A2 衝刺計畫</h2><p style={{fontSize:12,color:C.textMuted,marginTop:4}}>每天 15-20 分鐘 · 聽說讀寫 + KNM</p></div>
          <div style={S.progressBar}><div style={{...S.progressFill,width:`${(completedDays.size/30)*100}%`}}/><span style={S.progressText}>{completedDays.size}/30 天</span></div>
          {WEEK_PLAN.map(w=>(
            <div key={w.week} style={S.weekCard}>
              <div style={S.weekHeader}><span style={{fontSize:10,fontWeight:800,color:C.accent,letterSpacing:"0.1em"}}>WEEK {w.week}</span><span style={{fontSize:14,fontWeight:700,color:C.text}}>{w.title}</span></div>
              <div style={S.weekDays}>{w.days.map((d,i)=>{
                const avail=d&&COURSE_DATA[d];const done=d&&completedDays.has(d);
                return <div key={i} style={{...S.weekDay,...(avail?S.weekDayOn:{}),...(done?S.weekDayDone:{}),cursor:avail?"pointer":"default"}} onClick={()=>{if(avail){setCurrentDay(d);setActiveTab(0);}}}>
                  <span style={{fontSize:10,color:C.textMuted,display:"block"}}>{d?DAY_LABELS[d]||`D${d}`:"—"}</span>
                  {done&&<span style={{position:"absolute",top:1,right:3,fontSize:9,color:C.green}}>✓</span>}
                </div>;
              })}</div>
            </div>
          ))}
        </div>
      )}

      {activeTab===3&&(
        <div style={S.content}>
          <div style={{textAlign:"center",marginBottom:20}}><h2 style={{fontSize:20,fontWeight:800,color:C.text,margin:0}}>單字本 — {Object.values(COURSE_DATA).reduce((s,d)=>s+d.vocab.length,0)} 個單字</h2></div>
          {Object.entries(COURSE_DATA).map(([n,d])=>(
            <div key={n} style={S.vocabGroup}>
              <div style={S.vocabGroupH}>Dag {n} — {d.theme} ({d.themeZh})</div>
              {d.vocab.map((v,i)=><div key={i} style={S.vocabRow}><div style={{fontSize:14,fontWeight:700,color:C.text}}>{v.nl}</div><div style={{fontSize:11,color:C.textMuted,marginTop:1}}>{v.zh}</div><div style={{fontSize:11,color:C.textDim,fontStyle:"italic",marginTop:3}}>{v.example}</div></div>)}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function Sec({icon,title,sub,children}){
  const[open,setOpen]=useState(true);
  return<div style={S.sec}><div style={S.secH} onClick={()=>setOpen(!open)}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:18}}>{icon}</span><div><span style={{fontSize:14,fontWeight:700,color:C.text}}>{title}</span><span style={{fontSize:11,color:C.textMuted,marginLeft:8}}>{sub}</span></div></div><span style={{fontSize:9,color:C.textDim,transition:"transform .2s",transform:open?"rotate(180deg)":"rotate(0)"}}>▼</span></div>{open&&<div style={{padding:"0 16px 14px"}}>{children}</div>}</div>;
}

const C={bg:"#0d1117",surface:"#161b22",border:"#30363d",borderLight:"#21262d",accent:"#e8663c",accentSoft:"rgba(232,102,60,.12)",accentText:"#ff8c61",text:"#e6edf3",textMuted:"#8b949e",textDim:"#6e7681",green:"#3fb950",greenSoft:"rgba(63,185,80,.12)",blue:"#58a6ff",blueSoft:"rgba(88,166,255,.1)",you:"#1f6feb",youSoft:"rgba(31,111,235,.15)",purple:"#bc8cff",purpleSoft:"rgba(188,140,255,.12)"};

const S={
  container:{fontFamily:"'Nunito','Noto Sans TC',sans-serif",background:C.bg,color:C.text,minHeight:"100vh",maxWidth:640,margin:"0 auto"},
  header:{position:"sticky",top:0,zIndex:100,background:C.surface,borderBottom:`1px solid ${C.border}`},
  headerTop:{display:"flex",alignItems:"center",padding:"14px 20px 6px"},
  logo:{display:"flex",alignItems:"center",gap:12},
  logoTitle:{fontSize:17,fontWeight:800,letterSpacing:"-.02em",color:C.text},
  logoSub:{fontSize:11,color:C.textMuted,marginTop:1},
  tabs:{display:"flex",padding:"0 8px",overflowX:"auto"},
  tab:{flex:"0 0 auto",padding:"9px 12px",background:"none",border:"none",borderBottom:"2px solid transparent",color:C.textMuted,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"inherit",whiteSpace:"nowrap"},
  tabActive:{color:C.accent,borderBottomColor:C.accent},
  content:{padding:"16px 16px 80px"},
  dayNav:{display:"flex",alignItems:"center",justifyContent:"space-between",background:C.surface,borderRadius:16,padding:"18px 14px",marginBottom:18,border:`1px solid ${C.border}`},
  navBtn:{width:38,height:38,borderRadius:10,background:C.accentSoft,border:"none",color:C.accent,fontSize:16,fontWeight:700,cursor:"pointer",fontFamily:"inherit"},
  dayLabel:{fontSize:11,fontWeight:800,color:C.accent,letterSpacing:".12em"},
  examBadge:{fontSize:10,fontWeight:700,color:C.purple,background:C.purpleSoft,padding:"3px 8px",borderRadius:6,marginTop:4,display:"inline-block"},
  sec:{background:C.surface,borderRadius:14,border:`1px solid ${C.border}`,marginBottom:12,overflow:"hidden"},
  secH:{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"13px 16px",cursor:"pointer",userSelect:"none"},
  vocabCard:{background:C.bg,borderRadius:10,padding:"10px 12px",border:`1px solid ${C.borderLight}`},
  vocabNl:{fontSize:15,fontWeight:700,color:C.accentText},
  ctxBox:{fontSize:12,color:C.textMuted,padding:"8px 12px",background:C.blueSoft,borderRadius:8,marginBottom:10,borderLeft:`3px solid ${C.blue}`},
  dlg:{padding:"7px 11px",background:C.bg,borderRadius:"10px 10px 10px 3px",border:`1px solid ${C.borderLight}`,maxWidth:"88%"},
  dlgYou:{padding:"7px 11px",background:C.youSoft,borderRadius:"10px 10px 3px 10px",border:"1px solid rgba(31,111,235,.25)",maxWidth:"88%",alignSelf:"flex-end"},
  dlgSpeaker:{fontSize:10,fontWeight:700,color:C.textMuted,display:"block",marginBottom:1},
  input:{width:"100%",padding:"9px 11px",background:C.bg,border:`1px solid ${C.border}`,borderRadius:8,color:C.text,fontSize:13,fontFamily:"inherit",resize:"none",outline:"none",boxSizing:"border-box"},
  btnCheck:{marginTop:5,padding:"5px 12px",background:C.accentSoft,border:"none",borderRadius:7,color:C.accent,fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:"inherit"},
  answerBox:{marginTop:6,padding:"9px 11px",background:C.greenSoft,borderRadius:8,fontSize:13,color:C.green,lineHeight:1.6},
  infoBox:{padding:"11px 13px",background:C.bg,borderRadius:10,fontSize:13,color:C.text,lineHeight:1.6,border:`1px solid ${C.borderLight}`},
  goldenBox:{padding:"14px",background:"linear-gradient(135deg,rgba(232,102,60,.08),rgba(255,140,97,.04))",borderRadius:12,border:"1px solid rgba(232,102,60,.2)",textAlign:"center"},
  btnDone:{padding:"13px 28px",background:C.accent,border:"none",borderRadius:12,color:"#fff",fontSize:15,fontWeight:700,cursor:"pointer",fontFamily:"inherit"},
  doneBadge:{padding:"13px 22px",background:C.greenSoft,borderRadius:12,color:C.green,fontSize:15,fontWeight:700},
  examCard:{background:C.surface,borderRadius:14,border:`1px solid ${C.border}`,padding:16,marginBottom:12},
  progressBar:{position:"relative",height:28,background:C.surface,borderRadius:14,border:`1px solid ${C.border}`,marginBottom:18,overflow:"hidden"},
  progressFill:{position:"absolute",top:0,left:0,height:"100%",background:"linear-gradient(90deg,#e8663c,#ff8c61)",borderRadius:14,transition:"width .5s"},
  progressText:{position:"absolute",width:"100%",textAlign:"center",lineHeight:"28px",fontSize:12,fontWeight:700,color:C.text,zIndex:1},
  weekCard:{background:C.surface,borderRadius:14,border:`1px solid ${C.border}`,marginBottom:12,overflow:"hidden"},
  weekHeader:{padding:"12px 16px",display:"flex",alignItems:"center",gap:10,borderBottom:`1px solid ${C.borderLight}`},
  weekDays:{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3,padding:6},
  weekDay:{padding:"8px 3px",borderRadius:7,textAlign:"center",background:C.bg,opacity:.35,position:"relative"},
  weekDayOn:{opacity:1,background:C.bg,border:`1px solid ${C.borderLight}`},
  weekDayDone:{background:C.greenSoft,border:"1px solid rgba(63,185,80,.3)"},
  vocabGroup:{background:C.surface,borderRadius:14,border:`1px solid ${C.border}`,marginBottom:12,overflow:"hidden"},
  vocabGroupH:{padding:"10px 16px",fontSize:13,fontWeight:700,color:C.accentText,borderBottom:`1px solid ${C.borderLight}`,background:C.accentSoft},
  vocabRow:{padding:"8px 16px",borderBottom:`1px solid ${C.borderLight}`},
};

export default DutchA2App;
